CREATE DATABASE pmprep35;
CREATE TABLE users (id SERIAL PRIMARY KEY, email VARCHAR(300), password_digest VARCHAR(400) );
ALTER TABLE users ADD COLUMN name VARCHAR(400);
CREATE TABLE stories(id SERIAL PRIMARY KEY, name VARCHAR(50), email VARCHAR(300), story VARCHAR(1000));

CREATE TABLE contact(id SERIAL PRIMARY KEY, name VARCHAR(50), email VARCHAR(300), message VARCHAR(1000));
ALTER TABLE contact RENAME TO contacts;
